// 台挑估估王 — daily slider-guess game using real government statistics
// (../north-vs-south/data/{counties,indicators,values}.json).
//
// Rounds are authored data (puzzles.json, generated by tools/gen-puzzles.mjs)
// so a given puzzle id is identical for every player, forever. Min/max slider
// bounds are always recomputed client-side from values.json — never baked in —
// so a future data correction fixes the bounds for old puzzles too.
//
// Routing: /projects/slide-and-guess/        → today's puzzle (Asia/Taipei)
//          /projects/slide-and-guess/?p=7    → puzzle with permanent id 7

import {
  taipeiToday, daysBetween, esc, readStore, writeStore, share,
  scheduleRollover, setupOverlayHideLogic, populateSwitcher, loadVersion,
} from '/projects/challenge.js';

const ROUNDS = 5;
const STORE_KEY = 'slideandguess.v1';
const FIRST_DATE = '2026-09-30';

// ── DEBUG ────────────────────────────────────────────────────────────────────
// Flip to true while developing locally, then flip back before committing.
// Regardless of this flag, the browser console always has:
//   sag.replay()       restart the game on screen
//   sag.replayAll()    wipe every saved game
//   sag.state          the live game state object
const DEBUG = true;
// ─────────────────────────────────────────────────────────────────────────────

const VERDICTS = [
  { min: 90, label: '準' },
  { min: 70, label: '近' },
  { min: 40, label: '可' },
  { min: 0, label: '問號' },
];

const pad3 = n => String(n).padStart(3, '0');

function fmtNum(n) {
  const rounded = Math.round(n * 100) / 100;
  return rounded.toLocaleString('zh-TW');
}

/* ---------- entry point ---------- */

export async function mountSlide(cfg) {
  // VERSION bumps on every deploy, so tagging puzzles.json with it busts the
  // browser/mobile cache exactly when its content changed, instead of
  // forcing a fresh download on every load.
  const version = await fetch('VERSION', { cache: 'no-store' })
    .then(r => (r.ok ? r.text() : ''))
    .then(t => t.trim())
    .catch(() => '');
  const bust = v => (v ? `?v=${encodeURIComponent(v)}` : '');

  const [counties, indicators, values, puzzles] = await Promise.all([
    fetch('../north-vs-south/data/counties.json').then(r => r.json()),
    fetch('../north-vs-south/data/indicators.json').then(r => r.json()),
    fetch('../north-vs-south/data/values.json').then(r => r.json()),
    fetch('puzzles.json' + bust(version)).then(r => r.json()),
  ]);

  const byPuzzleId = new Map(puzzles.map(p => [p.date, p]));
  const countyById = new Map(counties.map(c => [c.id, c]));
  const indicatorById = new Map(indicators.map(i => [i.id, i]));

  // rows for (indicator, year) — used for bounds, the actual value, and the
  // fun-fact extremes. Cached lazily since the same indicator repeats across days.
  const rowsCache = new Map();
  function rowsFor(indicatorId, year) {
    const key = `${indicatorId}::${year}`;
    if (!rowsCache.has(key)) {
      rowsCache.set(key, values.filter(v => v.indicator === indicatorId && v.year === year && countyById.has(v.county)));
    }
    return rowsCache.get(key);
  }

  function boundsFor(indicatorId, year) {
    const rows = rowsFor(indicatorId, year);
    const vals = rows.map(r => r.value);
    return { min: Math.min(...vals), max: Math.max(...vals), rows };
  }

  // Round the real data bounds out to a "nice" slider range: 0 as the floor
  // when the real min is already small, and the max rounded up to 2
  // significant figures (21232 -> 22000, 7324 -> 7400) so the slider has
  // round numbers at its ends instead of an arbitrary data value.
  function niceRoundUp(n) {
    if (n <= 0) return n;
    const digits = Math.floor(Math.log10(n)) + 1;
    const magnitude = Math.pow(10, Math.max(digits - 2, 0));
    return Math.ceil(n / magnitude) * magnitude;
  }

  function niceBounds(min, max) {
    return {
      min: (min > 0 && min < 250) ? 0 : min,
      max: niceRoundUp(max),
    };
  }

  /* ---------- which date? ---------- */

  const params = new URLSearchParams(location.search);
  const debugReplay = DEBUG && params.get('replay') === '1';

  let today = taipeiToday();
  const requestedId = Number(params.get('p'));
  let dateKey = today;
  let isArchive = false;
  let blocked = false;

  if (Number.isInteger(requestedId) && requestedId >= 1) {
    const [year, month, day] = FIRST_DATE.split('-').map(Number);
    const firstDate = new Date(Date.UTC(year, month - 1, day));
    const targetDate = new Date(firstDate.getTime() + (requestedId - 1) * 86400000);
    const targetKey = `${targetDate.getUTCFullYear()}-${String(targetDate.getUTCMonth() + 1).padStart(2, '0')}-${String(targetDate.getUTCDate()).padStart(2, '0')}`;
    const isFuture = targetKey > today;
    blocked = isFuture && !DEBUG;
    if (!blocked) {
      dateKey = targetKey;
      isArchive = dateKey !== today;
    }
  }

  if (params.has('p') && !isArchive && !DEBUG) {
    try { history.replaceState(null, '', './'); } catch (e) { /* non-fatal */ }
  }

  /* ---------- shell (built once) ---------- */

  document.body.innerHTML = `
<div class="topbar">
  <div class="brand">
    <h1><a href="./" id="homeLink">${esc(cfg.shareTitle)} </a><span id="pno">#001</span></h1>
    <div class="stats"><span></span></div>
    <div class="switcher" id="switcher"></div>
  </div>
</div>
<div class="progressWrap"><div class="progressBar" id="pbar"></div></div>

<div class="wrap">
  <div class="archive-banner" id="archiveBanner"></div>
  <div class="stats" style="margin-bottom:2px;">
    <span>第 <b id="rno">1</b> / ${ROUNDS} 題</span>
  </div>
  <div class="roundDots" id="dots"></div>
  <p class="question" id="qtext"></p>

  <div class="slidecard">
    <div class="guessval" id="guessVal">0<span id="guessUnit"></span></div>
    <div class="slider-row">
      <input type="range" id="slider" min="0" max="100" step="1" value="50">
      <div class="range-labels"><span id="rangeMin"></span><span id="rangeMax"></span></div>
    </div>
    <div class="revealbar" id="revealBar" style="display:none;"></div>
    <div class="verdict" id="verdict" style="display:none;"></div>
    <div class="funfact" id="funfact"></div>
  </div>

  <div class="actionrow">
    <button class="primary" id="btnConfirm">確認</button>
  </div>

  <a href="#" class="archive-link" id="scoreInfoLink">分數怎麼算？</a>
  <p class="funfact" id="scoreInfoText" style="display:none;">每小題滿分 100，總分 500。<br>分數 = 100 −（｜你猜的數字 − 實際數字｜ ÷ 全台 22 縣市中的最大值減最小值）× 100，四捨五入後最低 0 分、最高 100 分。完全猜中是 100 分，誤差達到全台最大值與最小值的差距（或以上）就是 0 分，誤差是這個差距的一半大概是 50 分。</p>
  <a href="#" class="archive-link" id="archiveLink">📅 玩以前的題目</a>
  <a href="#" class="archive-link" id="otherLink">其他挑戰</a>
  <p class="footer-note">
    ${cfg.footer}<br>
    純屬好玩<span class="ver" id="ver"></span>
  </p>
</div>

<div class="overlay" id="overlay">
  <div class="report">
    <h2 id="rpTitle"></h2>
    <p class="rp-quip">每天更了解台灣一點點</p>
    <div class="rp-score" id="rpScore"></div>
    <div class="rp-rounds" id="rpRounds"></div>
    <div class="rp-stack">
      <p class="rp-quip">🔥 每天 00:00 更新題目</p>
      <button id="rpShare" class="primary">分享結果</button>
      <button id="rpArchive">📅 玩以前的挑戰</button>
      <button id="rpOther">其他挑戰</button>
    </div>
    <p class="footer-note" style="margin-top:12px">${cfg.footer}</p>
  </div>
</div>

<div class="overlay wide" id="archive">
  <div class="panel">
    <div class="panel-hd">
      <h2>玩以前的挑戰</h2>
      <button class="x" id="arClose" aria-label="關閉">✕</button>
    </div>
    <p class="tab-hint">每天 00:00 出一題。以前的題目隨時可以補玩，成績會分開記錄。</p>
    <div id="arList"></div>
  </div>
</div>

<div class="overlay wide" id="other">
  <div class="panel">
    <div class="panel-hd">
      <h2>其他小遊戲</h2>
      <button class="x" id="otClose" aria-label="關閉">✕</button>
    </div>
    <div id="otGames" class="other-games"></div>
  </div>
</div>`;

  const $ = id => document.getElementById(id);
  const overlay = $('overlay');

  populateSwitcher($, cfg);
  loadVersion('VERSION');
  setupOverlayHideLogic($);
  document.addEventListener('keydown', e => {
    if (e.key === 'Escape' && $('overlay').classList.contains('show')) {
      e.preventDefault();
    }
  }, true);
  $('overlay').addEventListener('click', e => {
    if (e.target === $('overlay')) e.stopPropagation();
  }, true);

  /* ---------- state ---------- */

  let store = readStore(STORE_KEY);
  let rounds = [];
  let title = '';
  // guesses[i] is a number once answered, else null. Scores are always derived
  // from the guess + the data, never stored, so a data fix repairs old scores too.
  let state = { guesses: [], finished: false };

  const gameKey = dk => `d${dk}`;
  const answered = () => state.guesses.filter(g => g !== null).length;
  const isOver = () => state.finished || answered() >= rounds.length;

  function blankState() { return { guesses: Array(ROUNDS).fill(null), finished: false }; }

  function loadGame(dk) {
    const saved = store.games[gameKey(dk)];
    const s = blankState();
    if (saved && Array.isArray(saved.guesses) && saved.guesses.length === ROUNDS) {
      s.guesses = saved.guesses.slice();
      s.finished = Boolean(saved.finished);
    }
    return s;
  }

  function persist() {
    const g = store.games[gameKey(dateKey)] || {};
    store.games[gameKey(dateKey)] = { ...g, guesses: state.guesses, finished: state.finished };
    writeStore(STORE_KEY, store);
  }

  function scoreForRound(r, guess) {
    const { min, max, rows } = boundsFor(r.indicatorId, r.year);
    const actual = rows.find(row => row.county === r.countyId).value;
    const range = (max - min) || 1;
    return Math.min(100, Math.max(0, Math.round(100 * (1 - Math.abs(guess - actual) / range))));
  }

  function scoreFor(i) {
    const g = state.guesses[i];
    if (g === null) return 0;
    return scoreForRound(rounds[i], g);
  }

  const totalScore = () => rounds.reduce((n, _, i) => n + scoreFor(i), 0);

  /* ---------- render ---------- */

  // The round currently on screen. Distinct from "first unanswered round" —
  // after confirming a guess the reveal for that round stays on screen until
  // the player explicitly advances, even though it now counts as answered.
  let viewIndex = 0;

  function currentIndex() {
    const i = state.guesses.findIndex(g => g === null);
    return i === -1 ? rounds.length : i;
  }

  const RANK_LABEL_DESC = ['最高', '第二高', '第三高'];
  const RANK_LABEL_ASC = ['最少', '第二少', '第三少'];

  function funFactFor(r, actual, min, max, rows) {
    const county = countyById.get(r.countyId);
    const ind = indicatorById.get(r.indicatorId);
    if (max === min) return '';

    const sortedDesc = rows.slice().sort((a, b) => b.value - a.value);
    const rankDesc = sortedDesc.findIndex(row => row.county === r.countyId) + 1;
    const rankAsc = sortedDesc.length - rankDesc + 1;

    if (rankDesc <= 3) {
      const lowest = sortedDesc[sortedDesc.length - 1];
      return `你知道嗎？${esc(county.name)}是全台灣${esc(ind.name)}${RANK_LABEL_DESC[rankDesc - 1]}的，有 ${fmtNum(actual)} ${esc(ind.unit)}，`
        + `最少的是${esc(countyById.get(lowest.county).name)}，只有 ${fmtNum(lowest.value)}${esc(ind.unit)}。`;
    }
    if (rankAsc <= 3) {
      const highest = sortedDesc[0];
      return `你知道嗎？${esc(county.name)}是全台灣${esc(ind.name)}${RANK_LABEL_ASC[rankAsc - 1]}的，只有 ${fmtNum(actual)} ${esc(ind.unit)}，`
        + `最多的是${esc(countyById.get(highest.county).name)} ${fmtNum(highest.value)}${esc(ind.unit)}。`;
    }
    return '';
  }

  function updateProgress() {
    $('dots').innerHTML = rounds.map((_, n) =>
      `<i class="${state.guesses[n] !== null ? 'on' : (n === viewIndex ? 'now' : '')}"></i>`).join('');
    $('pbar').style.width = `${(answered() / rounds.length) * 100}%`;
    $('rno').textContent = String(Math.min(viewIndex + 1, rounds.length));
  }

  function renderQuestion() {
    const i = viewIndex;
    updateProgress();

    if (i >= rounds.length) return;

    const r = rounds[i];
    const ind = indicatorById.get(r.indicatorId);
    const county = countyById.get(r.countyId);
    const { min: realMin, max: realMax } = boundsFor(r.indicatorId, r.year);
    const { min, max } = niceBounds(realMin, realMax);

    $('qtext').innerHTML = `<span class="q-text">${esc(county.name)}的${esc(ind.name)}是多少？<br><span class="q-unit">（${r.year}，單位：${esc(ind.unit)}）</span>`
      + `${ind.definition ? ` <br><a href="#" class="q-info">${esc(ind.name)} 是什麼？</a>` : ''}</span>`
      + `${ind.definition ? `<div class="q-def" id="qDef" style="display:none;">${esc(ind.definition)}</div>` : ''}`;
    $('guessUnit').textContent = ` ${ind.unit}`;
    $('rangeMin').textContent = fmtNum(min);
    $('rangeMax').textContent = fmtNum(max);

    const isInteger = ind.unit === '人';
    const slider = $('slider');
    slider.min = isInteger ? Math.round(min) : min;
    slider.max = isInteger ? Math.round(max) : max;
    if (isInteger) {
      slider.step = 1;
      slider.value = Math.round((min + max) / 2);
    } else {
      const rawStep = (max - min) > 0 ? (max - min) / 200 : 0.01;
      slider.step = Math.max(0.01, Math.round(rawStep * 100) / 100);
      slider.value = Math.round(((min + max) / 2) * 100) / 100;
    }
    slider.disabled = false;
    $('guessVal').firstChild.textContent = fmtNum(Number(slider.value));

    $('revealBar').style.display = 'none';
    $('verdict').style.display = 'none';
    $('funfact').textContent = '';
    $('btnConfirm').textContent = '確認';
    $('btnConfirm').disabled = false;
  }

  function renderReveal(i) {
    const r = rounds[i];
    const { min: realMin, max: realMax, rows } = boundsFor(r.indicatorId, r.year);
    const { min, max } = niceBounds(realMin, realMax);
    const actual = rows.find(row => row.county === r.countyId).value;
    const guess = state.guesses[i];
    const range = (max - min) || 1;
    const pct = v => Math.min(100, Math.max(0, ((v - min) / range) * 100));

    const guessPct = pct(guess);
    const actualPct = pct(actual);
    const overlapped = Math.abs(guessPct - actualPct) < 12;
    const guessLabel = overlapped ? '你估' : '你';

    const bar = $('revealBar');
    bar.style.display = '';
    bar.innerHTML = `
      <div class="rb-mark guess" style="left:${guessPct}%"></div>
      <div class="rb-mark actual" style="left:${actualPct}%"></div>
      <div class="rb-tag guess" style="left:${guessPct}%">${guessLabel} ${fmtNum(guess)}</div>
      <div class="rb-tag actual${overlapped ? ' stacked' : ''}" style="left:${actualPct}%">實際 ${fmtNum(actual)}</div>`;

    const s = scoreFor(i);
    const v = VERDICTS.find(x => s >= x.min);
    const verdict = $('verdict');
    verdict.style.display = '';
    verdict.innerHTML = `${v.label}<span class="pts">${s} / 100 分</span>`;

    $('funfact').textContent = funFactFor(r, actual, realMin, realMax, rows);

    const slider = $('slider');
    slider.disabled = true;
    slider.value = guess;

    $('btnConfirm').textContent = i === rounds.length - 1 ? '看今日成績' : '下一題';
    $('btnConfirm').disabled = false;
  }

  function render() {
    if (viewIndex >= rounds.length) return;
    if (state.guesses[viewIndex] !== null) renderReveal(viewIndex);
    else renderQuestion();
    updateProgress();
  }

  $('slider').addEventListener('input', e => {
    $('guessVal').firstChild.textContent = fmtNum(Number(e.target.value));
  });

  $('qtext').addEventListener('click', e => {
    if (!e.target.classList.contains('q-info')) return;
    e.preventDefault();
    const def = $('qDef');
    if (def) def.style.display = def.style.display === 'none' ? '' : 'none';
  });

  $('btnConfirm').addEventListener('click', () => {
    if (viewIndex >= rounds.length) return;
    if (state.guesses[viewIndex] === null) {
      // confirm this round's guess
      state.guesses[viewIndex] = Number($('slider').value);
      if (answered() >= rounds.length) state.finished = true;
      persist();
      renderReveal(viewIndex);
      updateProgress();
      return;
    }
    // advance to the next round, or to results after the last one
    viewIndex += 1;
    if (viewIndex >= rounds.length) { showResult(); return; }
    render();
  });

  /* ---------- result ---------- */

  const scoreEmoji = s => (s >= 80 ? '🟩' : s >= 50 ? '🟨' : '🟥');

  const roundLines = () => rounds.map((r, i) => {
    const ind = indicatorById.get(r.indicatorId);
    const county = countyById.get(r.countyId);
    const s = scoreFor(i);
    return `${esc(county.name)}${esc(ind.name)} ${scoreEmoji(s)}`;
  });

  function roundsHTML() {
    return rounds.map((r, i) => {
      const ind = indicatorById.get(r.indicatorId);
      const county = countyById.get(r.countyId);
      const s = scoreFor(i);
      return `<div class="rr"><span class="no">${i + 1}</span>`
        + `<span class="ind">${esc(county.name)}${esc(ind.name)}</span>`
        + `<span class="sc">${s}</span>`
        + `<span class="mk">${scoreEmoji(s)}</span></div>`;
    }).join('');
  }

  function shareText() {
    const puzzleNum = daysBetween(FIRST_DATE, dateKey) + 1;
    const s = totalScore();
    return `${title}\n${s} 分/${ROUNDS * 100} 分\n\n${roundLines().join('\n')}`
      + `\n\n台挑估估王 你敢來估嗎？ | 台灣大挑戰\n🔗 ${cfg.shareUrl}?p=${puzzleNum}`;
  }

  function showResult() {
    state.finished = true;
    persist();
    $('rpTitle').textContent = title;
    $('rpScore').textContent = `${totalScore()} / ${ROUNDS * 100}`;
    $('rpRounds').innerHTML = roundsHTML();
    overlay.classList.add('show');
  }

  $('rpShare').addEventListener('click', e => share(shareText(), e.currentTarget));
  $('rpOther').addEventListener('click', () => $('other').classList.add('show'));
  $('otClose').addEventListener('click', () => $('other').classList.remove('show'));
  $('otherLink').addEventListener('click', e => { e.preventDefault(); $('other').classList.add('show'); });
  $('scoreInfoLink').addEventListener('click', e => {
    e.preventDefault();
    const el = $('scoreInfoText');
    el.style.display = el.style.display === 'none' ? '' : 'none';
  });

  /* ---------- archive (玩以前的挑戰) ---------- */

  function savedGame(dk) {
    const g = store.games[gameKey(dk)];
    if (!g || !Array.isArray(g.guesses) || g.guesses.length !== ROUNDS) return null;
    const ans = g.guesses.filter(x => x !== null).length;
    if (!ans) return null;
    const puzzle = byPuzzleId.get(dk);
    const rs = puzzle ? puzzle.rounds : [];
    const hits = rs.reduce((n, r, i) => n + (g.guesses[i] !== null && scoreForRound(r, g.guesses[i]) >= 70 ? 1 : 0), 0);
    return { answered: ans, hits, finished: Boolean(g.finished) };
  }

  function openArchive() {
    const dates = [];
    const span = daysBetween(FIRST_DATE, today);
    for (let n = span; n >= 0; n--) {
      const [year, month, day] = FIRST_DATE.split('-').map(Number);
      const d = new Date(Date.UTC(year, month - 1, day));
      d.setUTCDate(d.getUTCDate() + n);
      dates.push(`${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-${String(d.getUTCDate()).padStart(2, '0')}`);
    }
    $('arList').innerHTML = dates.map((dk, idx) => {
      const isToday = dk === today;
      const s = savedGame(dk);
      const puzzleId = span - idx + 1;
      const status = !s ? '未挑戰'
        : s.finished ? `${s.hits}/${ROUNDS}`
        : `進行中 ${s.answered}/${ROUNDS}`;
      return `<button class="plist" data-id="${puzzleId}"${isToday && !isArchive ? ' disabled' : ''}>`
        + `<span class="pl-mid"><span class="pl-date">${esc(dk)}${isToday ? '（今天）' : ''}</span></span>`
        + `<span class="pl-status${s && s.finished ? ' done' : ''}">${status}</span></button>`;
    }).join('') || '<p class="tab-hint">還沒有以前的題目。</p>';
    $('archive').classList.add('show');
  }

  $('archiveLink').addEventListener('click', e => { e.preventDefault(); openArchive(); });
  $('rpArchive').addEventListener('click', openArchive);
  $('arClose').addEventListener('click', () => $('archive').classList.remove('show'));
  $('arList').addEventListener('click', e => {
    const b = e.target.closest('.plist');
    if (!b || b.disabled) return;
    location.href = `?p=${b.dataset.id}`;
  });

  /* ---------- game setup ---------- */

  function setDate(dk) {
    dateKey = dk;
    isArchive = dateKey !== today;
    const puzzle = byPuzzleId.get(dateKey);
    rounds = puzzle ? puzzle.rounds : [];
    const puzzleNum = daysBetween(FIRST_DATE, dateKey) + 1;
    title = `${cfg.shareTitle} #${pad3(puzzleNum)}`;
    if (debugReplay) {
      delete store.games[gameKey(dateKey)];
      writeStore(STORE_KEY, store);
    }
    state = loadGame(dateKey);
    viewIndex = currentIndex();
    if (DEBUG) {
      sag.state = state;
      console.log(`[台挑估估王] date=${dateKey}, ${rounds.length}/${ROUNDS} rounds`);
    }
    $('pno').textContent = `#${pad3(puzzleNum)}`;
    const banner = $('archiveBanner');
    if (blocked) {
      banner.innerHTML = '這一題還沒開放，先玩今天的吧。 <a href="./">回到今天</a>';
      banner.style.display = '';
    } else if (isArchive) {
      banner.innerHTML = `這是 ${dateKey} 的題目。 <a href="./">回到今天</a>`;
      banner.style.display = '';
    } else {
      banner.style.display = 'none';
    }
    overlay.classList.remove('show');
    render();
    if (isOver()) showResult();
  }

  /* ---------- console helpers ---------- */

  const sag = {
    replay() {
      delete store.games[gameKey(dateKey)];
      writeStore(STORE_KEY, store);
      setDate(dateKey);
    },
    replayAll() { store = { v: 1, games: {} }; writeStore(STORE_KEY, store); setDate(dateKey); },
    get rounds() { return rounds; },
    state,
  };
  window.sag = sag;

  setDate(dateKey);

  if (!isArchive) {
    scheduleRollover(newDate => {
      if (newDate !== today) {
        today = newDate;
        store = readStore(STORE_KEY);
        setDate(newDate);
      }
      return true;
    });
  }
}
